import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  pdf,
} from "@react-pdf/renderer";

type OCItem = {
  sku: string;
  quantity: number | string;
  notes: string;
};

type GenerateOCPdfParams = {
  companyName: string;
  customer: string;
  customerEmail: string;
  poNumber: string;
  ocNumber: string;
  ocDate: string;
  items: OCItem[];
};

const styles = StyleSheet.create({
  page: {
    padding: 36,
    fontSize: 10,
    fontFamily: "Helvetica",
    color: "#111827",
  },
  header: {
    marginBottom: 24,
    borderBottomWidth: 1,
    borderBottomColor: "#111827",
    paddingBottom: 12,
  },
  companyName: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 4,
  },
  title: {
    fontSize: 16,
    fontWeight: "bold",
    marginTop: 12,
  },
  section: {
    marginBottom: 16,
  },
  row: {
    flexDirection: "row",
    marginBottom: 4,
  },
  label: {
    width: 100,
    fontWeight: "bold",
  },
  value: {
    flex: 1,
  },
  table: {
    borderWidth: 1,
    borderColor: "#111827",
    marginTop: 10,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#f3f4f6",
    borderBottomWidth: 1,
    borderBottomColor: "#111827",
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#d1d5db",
  },
  cellSku: {
    width: "35%",
    padding: 6,
    borderRightWidth: 1,
    borderRightColor: "#d1d5db",
  },
  cellQty: {
    width: "15%",
    padding: 6,
    borderRightWidth: 1,
    borderRightColor: "#d1d5db",
  },
  cellNotes: {
    width: "50%",
    padding: 6,
  },
  footer: {
    marginTop: 28,
    fontSize: 9,
    color: "#4b5563",
  },
});

function OCDocument(params: GenerateOCPdfParams) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.companyName}>{params.companyName}</Text>
          <Text style={styles.title}>ORDER CONFIRMATION</Text>
        </View>

        <View style={styles.section}>
          <View style={styles.row}>
            <Text style={styles.label}>OC No:</Text>
            <Text style={styles.value}>{params.ocNumber}</Text>
          </View>

          <View style={styles.row}>
            <Text style={styles.label}>OC Date:</Text>
            <Text style={styles.value}>{params.ocDate}</Text>
          </View>

          <View style={styles.row}>
            <Text style={styles.label}>Customer:</Text>
            <Text style={styles.value}>{params.customer}</Text>
          </View>

          <View style={styles.row}>
            <Text style={styles.label}>Customer Email:</Text>
            <Text style={styles.value}>{params.customerEmail}</Text>
          </View>

          <View style={styles.row}>
            <Text style={styles.label}>PO Number:</Text>
            <Text style={styles.value}>{params.poNumber}</Text>
          </View>
        </View>

        <View style={styles.table}>
          <View style={styles.tableHeader}>
            <Text style={styles.cellSku}>SKU</Text>
            <Text style={styles.cellQty}>Quantity</Text>
            <Text style={styles.cellNotes}>Notes</Text>
          </View>

          {params.items.map((item, index) => (
            <View key={`${item.sku}-${index}`} style={styles.tableRow}>
              <Text style={styles.cellSku}>{item.sku}</Text>
              <Text style={styles.cellQty}>{String(item.quantity || "")}</Text>
              <Text style={styles.cellNotes}>{item.notes || ""}</Text>
            </View>
          ))}
        </View>

        <Text style={styles.footer}>
          This order confirmation has been generated by Order Engine based on
          the customer email and/or attachment received. Please review all
          commercial terms before sending.
        </Text>
      </Page>
    </Document>
  );
}

export async function generateOCPdfBuffer(params: GenerateOCPdfParams) {
  const instance = pdf(<OCDocument {...params} />);
  const blob = await instance.toBlob();
  const arrayBuffer = await blob.arrayBuffer();

  return Buffer.from(arrayBuffer);
}